spring:
  application:
    name: orderms
  datasource:
    url: jdbc:postgresql://localhost:5432/btgpactual
    username: postgres
    password: postgres
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
